name: Publish
on: [push]
jobs:
  push:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: educandu/inlets
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.tag }}
            ${{ env.DOCKER_IMAGE }}:latest
