name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE: educandu/inlets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - name: Get tag from build environment
        id: tag
        uses: ilDug/get-tag-action@v1.0.1
      - name: Authenticate with DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to DockerHub
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.version }}
            ${{ env.DOCKER_IMAGE }}:latest
